"""maintenance

Revision ID: 5c47bbb2b30e
Revises: d40ab309cdd2
Create Date: 2025-01-29 12:38:38.831016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c47bbb2b30e'
down_revision: Union[str, None] = 'd40ab309cdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.String(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('garage_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenances')
    # ### end Alembic commands ###
